### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: '.\\build'

### ISSUE THREAD

**Issue by miko1034** [addi00000/pegasus#13]
The error happens when you are creating your file.

FileNotFoundError: [WinError 3] The system cannot find the path specified: '.\\build'

**Comment by addi00000** [comment]
Are you using a newer version of python and have you downloaded all requirements?

**Comment by addi00000** [comment]
if exe is generated it should be fine otherwise please respond or if it is working please close the issue
