### ISSUE TITLE
Lots of errors

### ISSUE THREAD

**Issue by Smug246** [addi00000/pegasus#17]
First Error:
Traceback (most recent call last):
  File "<string>", line 535, in <module>
  File "<string>", line 69, in pegasus
  File "<string>", line 41, in main
  File "<string>", line 127, in __init__
  File "<string>", line 243, in grabTokens
KeyError: 'premium_type' 

Second Error:
Traceback (most recent call last):
  File "<string>", line 537, in <module>
  File "<string>", line 437, in cleanup
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'google-passwords.txt'

Third Error:
NameError: name 'exit' is not defined

**Comment by addi00000** [comment]
Both should be fixed in the latest commit.

Please test and close if fixed.

**Comment by Smug246** [comment]
alr those errors dont come up which is good but now theres an error in the grabbers that get created. you need to add "
from cryptography.fernet import Fernet" to the pegasus.py because when the file gets made the file changes to "WEBHOOK_URL = Fernet(b'blahblahblah". Thats the first issue which is an easy fix. Second issue it just doesnt send data to the webhook but doesnt create an error. might be something on my end idk.

**Comment by addi00000** [comment]
Try again newest

**Comment by Awire9966** [comment]
If it still dont work then just use rdimo's

**Comment by addi00000** [comment]
> If it still dont work then just use rdimo's

unhelpful reply and invalid opinon

**Comment by Smug246** [comment]
wont send to webhook but ima keep trying it think its something on my end coz i cant get logged rn. u can close issue
