### ISSUE TITLE
this is a scam

### ISSUE THREAD

**Issue by fdsmjkfjires** [addi00000/pegasus#18]
yo pls dont use this grabber the webhook in the code belinds to addi

**Comment by fdsmjkfjires** [comment]
> yo pls dont use this grabber the webhook in the code belinds to addi

its duel hooked basicaly

**Comment by mte0** [comment]
lol i doubt it, can you show where it does that in the code? @fdsmjkfjires

**Comment by fdsmjkfjires** [comment]
> lol i doubt it, can you show where it does that in the code? @fdsmjkfjires

<img width="812" alt="image" src="https://user-images.githubusercontent.com/96617924/172049462-abb97324-ad8d-4ee5-9ce6-3f109efeedd2.png">

**Comment by mte0** [comment]
tf lol what line is that at

**Comment by fdsmjkfjires** [comment]
i ran it myself ig they have all my passwords nd stuff fuck

**Comment by fdsmjkfjires** [comment]
> tf lol what line is that at

33

**Comment by mte0** [comment]
![Uploading 81BCC502-F8DC-4E83-B59C-7B700E27528C.jpeg…]()

**Comment by fdsmjkfjires** [comment]
man fuck im dead

**Comment by Kiwifuit** [comment]
Line 33 is where the script decodes the webhook you provide in `builder.py` though...

**Comment by addi00000** [comment]
Line 33 in the builder is empty and line 33 in the main is for your webhook

assuming this is a shitpost and closing
