### ISSUE TITLE
when running python builder.py it gives an error

### ISSUE THREAD

**Issue by MrGamerCreates** [addi00000/pegasus#20]
says file (file path) line 8, in <module> from alive_progress import alive_bar
ModuleNotFoundError: No module named alive_progress

any way to fix this>

**Comment by tanukieggs** [comment]
ya pip install alive_progress i think

**Comment by addi00000** [comment]
Install requirements like said in the readme

**Comment by mte0** [comment]
how are people this retarded?

**Comment by mte0** [comment]
hi adi

**Comment by mte0** [comment]
merge pr
