### ISSUE TITLE
error log: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Straight12** [addi00000/pegasus#6]
error log: 'NoneType' object is not callable

**Comment by TWIST-X7** [comment]
send friend request TWISTX7#9122

**Comment by Straight12** [comment]
add me

**Comment by addi00000** [comment]
I added some error handling that's getting triggered easily

![image](https://user-images.githubusercontent.com/81730200/163689390-fbeb814c-2df0-42b7-ba23-cb21b11c4f14.png)

If this is what you are seeing then nothing is wrong

**Comment by Straight12** [comment]
Yea but the injection not working 💀

**Comment by LocalSmail** [comment]
Injection was patched by discord.

**Comment by jinja365** [comment]
@Straight12  and @LocalSmail nope the injection still works as of now, just try again

**Comment by Straight12** [comment]
> @Straight12  and @LocalSmail nope the injection still works as of now, just try again

Alr thanks for telling me

**Comment by addi00000** [comment]
injection is getting iffy so idk.
